config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  root to: "home#index"

  get 'home/index'
  get 'terms' => 'pages#terms'
  get 'about' => 'pages#about'

  resource :contacts, only: [:new, :create], path_names: { :new => '' }
  resources :articles do
    resource :comments, only: [:create]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true
  validates :text, presence: true
  has_many :comments, dependent: :destroy
  validates_length_of :title, maximum: 140
  validates_length_of :text, maximum: 4000

  def subject
    title
  end

  def last_comment
    comments.last
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
  validates_length_of :body, maximum: 4000
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :email, presence: true
  validates :message, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    articles_path
  end

  private

  def configure_permitted_parameters
     devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end 
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  before_action :authenticate_user!, except: [:show, :index]

  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
  end

  def create
    @article = Article.new(article_params)
    @article.author = current_user.username
    if @article.save
      redirect_to @article
    else
      render action: 'new'
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    if @article.update(article_params)
      redirect_to @article
    else
      render action: 'edit'
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to articles_path
  end

  private

  def article_params
    params.require(:article).permit(:title,:text)
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  before_action :authenticate_user!

  def create
    @article = Article.find(params[:article_id])
    comment = @article.comments.new(comment_params)
    comment.author = current_user.username
    comment.save
    redirect_to article_path(@article)
  end

  private

  def comment_params
    params.require(:comment).permit(:author, :body)
  end
  
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  def new
  end

  def create
    @contact = Contact.new(contact_params)
    if @contact.valid?
      @contact.save
    else
      render action: 'new'
    end
  end

  private

  def contact_params
    params.require(:contact).permit(:email, :message)
  end
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def terms
  end

  def about
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/edit.html.erb
<h1>Edit article</h1>

<%= form_for :article, url: article_path(@article), method: :put do |f| %>
  <% if @article && @article.errors.any? %>
    <p>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </p>
  <% end %>
  <p>
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :text %><br />
    <%= f.text_area :text %>
  </p>

  <p>
    <%= f.submit %>
  </p>

<% end %>

app/views/articles/index.html.erb
<div class="container">
<% @articles.each do |article| %>

  <h3><%= article.title %></h3>

  <p>
    <%= article.text %>
  </p>

  <p>
    <%= link_to 'Read', article_path(article), class: 'btn btn-primary' %>
  </p>
  <p>
  <% if user_signed_in? and current_user.username == article.author %>
    <%= link_to 'Edit', edit_article_path(article), class: 'btn btn-default btn-xs' %> | 
    <%= link_to 'Delete', article_path(article), method: :delete, data: { confirm: 'Are you sure?'}, class: 'btn btn-default btn-xs' %>
  <% end %>
  </p>

  <hr />

<% end %>
</div>

app/views/articles/new.html.erb
<div class="container">
<h2>New article</h2>

<%= simple_form_for :article, url: articles_path do |f| %>
  <div class="form-inputs">
    <%= f.input :title, autofocus: true %>
    <%= f.input :text %>
  </div>

  <div class="form-actions">
    <%= f.submit 'Create article' , class: 'btn btn-primary' %>
  </div>
<% end %>

</div>

app/views/articles/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6">
    <h1><%= @article.title %></h1>
    <p>
      <%= @article.text %>
    </p>
  <p>
  <% if user_signed_in? and current_user.username == @article.author %>
    <%= link_to 'Edit', edit_article_path(@article), class: 'btn btn-default btn-xs' %> | 
    <%= link_to 'Delete', article_path(@article), method: :delete, data: { confirm: 'Are you sure?'}, class: 'btn btn-default btn-xs' %>
  <% end %>
  </p>
    <h4>Comments:</h4>
    <p>
    <% @article.comments.each do |comment|%>
      <p>
        <i><%= comment.author %> said:</i><br />
        <%= comment.body %>
      </p>
      <hr />
    <% end %>
    </p>
    </div>
  </div>

  <h4>Add comment:</h4>
  <div class="row">
    <div class="col-md-6">
    <p>
    <%= form_for([@article, @article.comments.build]) do |f| %>
      <% if user_signed_in? %>
      <p>
        <%= current_user.username %>
      </p>
      <% else %>
      <p>
        <%= link_to 'Log in', new_user_session_path %> to leave comment 
      </p>
      <% end %>

      <p>
        <%= f.label :body %><br />
        <%= f.text_area :body, class: 'form-control', rows: '3' %>
      </p>

      <p>
        <%= f.submit 'Add comment', class: 'btn btn-primary' %>
      </p>

    <% end %>
    </p>
    </div>
  </div>
</div>

app/views/contacts/create.html.erb
<h1>Thank you</h1>

app/views/contacts/new.html.erb
<div class="container">
  <h2><%= t('contacts.contact_us') %></h2>

  <%= simple_form_for :contact, url: contacts_path do |f| %>
    <div class="form-inputs">
      <%= f.input :email, autofocus: true %>
      <%= f.input :message %>
    </div>

    <div class="form-actions">
      <%= f.submit 'Send message' , class: 'btn btn-primary' %>
    </div>
  <% end %>

</div>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/articles">Blog</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to 'New Article', new_article_path %></li>
            <li><%= link_to 'Contact', contacts_path %></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
              <p class="navbar-text">Hello, <%= current_user.username %></p>
              <li><%= link_to 'Log out', destroy_user_session_path, method: :delete, data: { confirm: 'Are you leaving already?'} %></li>
            <% else %>
              <li><%= link_to 'Log in', new_user_session_path %></li>
              <li><%= link_to 'Sign up', new_user_registration_path %></li>
            <% end %>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>
    <div class="container">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    <%= yield %>
    </div>

  </body>
</html>

app/views/pages/about.html.erb
<h1>About us</h1>
<p>Welcome to my simple blog</p>

app/views/pages/terms.html.erb
<h1>Terms of Service</h1>
<p>Do whatever you want</p>